-- Add UNAVAILABLE and UNAVAILABLE_REVERSED to NeedStatus enum
ALTER TYPE "NeedStatus" ADD VALUE IF NOT EXISTS 'UNAVAILABLE';
ALTER TYPE "NeedStatus" ADD VALUE IF NOT EXISTS 'UNAVAILABLE_REVERSED';

-- Add UNAVAILABLE and UNAVAILABLE_REVERSED to FulfillmentEventType enum
ALTER TYPE "FulfillmentEventType" ADD VALUE IF NOT EXISTS 'UNAVAILABLE';
ALTER TYPE "FulfillmentEventType" ADD VALUE IF NOT EXISTS 'UNAVAILABLE_REVERSED';
