name: friends-crm
services:
- name: web
  source_dir: /
  github:
    repo: richard-brash/friends
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 4000
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "4000"
